packages:
  - packages/**

allowBuilds:
  esbuild: true

catalogs:
  dev:
    "@arethetypeswrong/core": 0.18.3
    "@react-router/dev": 8.2.0
    "@react-router/fs-routes": ^8.2.0
    "@types/node": 26.1.1
    "@typescript/native-preview": 7.0.0-dev.20260604.1
    "@virtual-live-lab/tsconfig": 2.1.23
    eslint: 10.6.0
    oxlint: 1.68.0
    pkg-pr-new: 0.0.75
    publint: 0.3.21
    react-router: 8.2.0
    typescript: 7.0.2
    unplugin-unused: 0.5.7
    vite: 8.0.16
    vite-plus: 0.1.24
  prod:
    "@oxlint/plugins": 1.68.0
    "@platformatic/vfs": 0.4.0
    gunshi: 0.34.0
    oxc-parser: 0.134.0
    pathe: ^2.0.3
    type-fest: ^5.6.0
    valibot: 1.4.1

minimumReleaseAgeExclude:
  - gunshi@0.34.0

saveExact: true
