import { defineRule } from "@oxlint/plugins";
import type { Context, ESTree, Settings } from "@oxlint/plugins";
import {
  classifyModuleOutletContext,
  NEAREST_OUTLET_CONTEXT_TYPE,
  toolkitTypesSpecifier,
} from "react-router-toolkit";

import type { ReactRouterToolkitSettings, RouteModuleInfo } from "../settings";
import { readSettings } from "../settings";
import { getRuleDocsURL } from "../utils";

type MessageIds =
  // Parent role: a route renders `<Outlet context={...}>`.
  | "missingOutletContextAnnotation"
  | "useSatisfiesNotAs"
  | "inlineOutletContextType"
  | "outletContextTypeNotLocal"
  | "outletContextTypeNotExported"
  | "outletSpreadAttribute"
  | "outletInExportedComponent"
  // Child role: a route calls `useOutletContext()`.
  | "missingOutletContextType"
  | "outdatedOutletContextType"
  | "ambiguousParentOutletContext"
  | "parentOutletPassesNoContext";

const typeSafeOutletContext = defineRule({
  meta: {
    type: "suggestion",
    fixable: "code",
    docs: {
      description:
        "Keep outlet context types in sync without writing them twice: require `<Outlet context={...}>` to be annotated with `satisfies <ExportedType>`, and auto-fill `useOutletContext<NearestOutletContext>()` (and its `./+toolkit-types/<route>` import, generated by `react-router-toolkit typegen`) in descendant routes.",
      url: getRuleDocsURL("type-safe-outlet-context"),
    },
    messages: {
      missingOutletContextAnnotation:
        "Annotate the outlet context with `satisfies <ExportedType>` so descendant routes can reuse the type.",
      useSatisfiesNotAs: "Use `satisfies` instead of `as` for the outlet context type.",
      inlineOutletContextType:
        "Extract the outlet context type into an exported type alias in this module and reference it with `satisfies`.",
      outletSpreadAttribute:
        "Do not spread attributes onto <Outlet>; pass `context` explicitly with `satisfies <ExportedType>` so descendant routes can infer it.",
      outletInExportedComponent:
        "Render <Outlet> from this route's default export (or a non-exported local component it renders), not from an exported component. React Router renders the default export, so an Outlet in an exported component does not pass context to descendant routes.",
      outletContextTypeNotLocal:
        'Type "{{name}}" must be a type alias defined in this module so descendant routes can import it from here.',
      outletContextTypeNotExported:
        'Type "{{name}}" must be exported so descendant routes can import it.',
      missingOutletContextType:
        "useOutletContext() should be typed with the generated `{{expected}}` (run `react-router-toolkit typegen` if the type module does not exist yet).",
      outdatedOutletContextType:
        "useOutletContext type argument should be the generated `{{expected}}` to match the parent outlet context.",
      ambiguousParentOutletContext:
        "The parent layout passes outlet context with differing types; annotate useOutletContext manually.",
      parentOutletPassesNoContext:
        "The nearest layout renders <Outlet> without context, so useOutletContext() is always undefined here.",
    } satisfies Record<MessageIds, string>,
  },
  createOnce: (context) => {
    let settingsSource: Readonly<Settings> | undefined;
    let settings: ReactRouterToolkitSettings | null = null;

    // Resolved per file in `before()`. One module file can be registered under several route ids
    // (`route("a", "x.tsx")` / `route("b", "x.tsx")`), so every registration is collected — the
    // child role must consider all of their parents, not just the first match.
    let selfEntries: RouteModuleInfo[] = [];
    let routeModules: Record<string, RouteModuleInfo> = {};

    // Parent role: collected from this file's own AST. The set of <Outlet>s is derived at
    // `Program:exit` from the whole program (see `classifyOutlets`), so we only collect the type
    // aliases needed to validate `satisfies <ExportedType>` annotations here.
    let localTypeAliases = new Map<string, ESTree.TSTypeAliasDeclaration>();
    let exportedNames = new Set<string>();

    // Child role.
    let useOutletContextNames = new Set<string>();
    let knownNames = new Set<string>();
    let calls: ESTree.CallExpression[] = [];
    let lastImport: ESTree.ImportDeclaration | null = null;

    return {
      before: () => {
        selfEntries = [];
        routeModules = {};
        localTypeAliases = new Map();
        exportedNames = new Set();
        useOutletContextNames = new Set();
        knownNames = new Set();
        calls = [];
        lastImport = null;

        if (context.settings !== settingsSource) {
          settingsSource = context.settings;
          settings = readSettings(context.settings);
        }
        if (settings === null || settings.routeModules === undefined) {
          return false;
        }
        routeModules = settings.routeModules;
        selfEntries = Object.values(routeModules).filter(
          (entry) => entry.physicalFile === context.physicalFilename,
        );
        return selfEntries.length > 0;
      },

      ImportDeclaration: (node) => {
        lastImport = node;
        const source = node.source.value;
        for (const specifier of node.specifiers) {
          knownNames.add(specifier.local.name);
          if (
            specifier.type === "ImportSpecifier" &&
            specifier.imported.type === "Identifier" &&
            (source === "react-router" || source === "react-router-dom") &&
            specifier.imported.name === "useOutletContext"
          ) {
            useOutletContextNames.add(specifier.local.name);
          }
        }
      },

      TSTypeAliasDeclaration: (node) => {
        knownNames.add(node.id.name);
        localTypeAliases.set(node.id.name, node);
        if (node.parent.type === "ExportNamedDeclaration") {
          exportedNames.add(node.id.name);
        }
      },

      TSInterfaceDeclaration: (node) => {
        knownNames.add(node.id.name);
      },

      ExportNamedDeclaration: (node) => {
        for (const specifier of node.specifiers) {
          if (specifier.local.type === "Identifier") {
            exportedNames.add(specifier.local.name);
          }
        }
      },

      CallExpression: (node) => {
        if (node.callee.type === "Identifier" && useOutletContextNames.has(node.callee.name)) {
          calls.push(node);
        }
      },

      "Program:exit": () => {
        if (selfEntries.length === 0) {
          return;
        }
        const { reachable, exportedComponent } = classifyOutlets(context.sourceCode.ast);
        reportParentRole(context, reachable, exportedComponent, localTypeAliases, exportedNames);
        reportChildRole(context, selfEntries, routeModules, calls, knownNames, lastImport);
      },
    };
  },
});

// Parent role is report-only: any outlet context that is not `satisfies <local exported type
// alias>` is an error the developer must fix by hand. We deliberately do not auto-fix here —
// silently adding `export` (or rewriting `as` to `satisfies`) changes a module's public surface or
// type semantics, which is too invasive for a lint fix.
//
// `reachableOutlets` are the <Outlet>s the route actually renders (validated below);
// `exportedComponentOutlets` are <Outlet>s declared in exported (non-default) components — they
// never pass context to children, so they are flagged outright.
function reportParentRole(
  context: Context,
  reachableOutlets: readonly ESTree.JSXOpeningElement[],
  exportedComponentOutlets: readonly ESTree.JSXOpeningElement[],
  localTypeAliases: ReadonlyMap<string, ESTree.TSTypeAliasDeclaration>,
  exportedNames: ReadonlySet<string>,
): void {
  for (const outlet of exportedComponentOutlets) {
    context.report({ node: outlet, messageId: "outletInExportedComponent" });
  }

  const contextProps: { attr: ESTree.JSXAttribute; expr: ESTree.Expression | null }[] = [];
  for (const outlet of reachableOutlets) {
    for (const attribute of outlet.attributes) {
      if (attribute.type === "JSXSpreadAttribute") {
        context.report({ node: attribute, messageId: "outletSpreadAttribute" });
        continue;
      }
      if (attribute.name.type !== "JSXIdentifier" || attribute.name.name !== "context") {
        continue;
      }
      const value = attribute.value;
      const expr =
        value !== null &&
        value.type === "JSXExpressionContainer" &&
        value.expression.type !== "JSXEmptyExpression"
          ? value.expression
          : null;
      contextProps.push({ attr: attribute, expr });
    }
  }

  for (const { attr, expr } of contextProps) {
    if (expr === null) {
      context.report({ node: attr, messageId: "missingOutletContextAnnotation" });
      continue;
    }
    if (expr.type === "TSAsExpression") {
      context.report({ node: expr, messageId: "useSatisfiesNotAs" });
      continue;
    }
    if (expr.type !== "TSSatisfiesExpression") {
      context.report({ node: expr, messageId: "missingOutletContextAnnotation" });
      continue;
    }

    const typeNode = expr.typeAnnotation;
    if (
      typeNode.type !== "TSTypeReference" ||
      typeNode.typeName.type !== "Identifier" ||
      typeNode.typeArguments !== null
    ) {
      context.report({ node: typeNode, messageId: "inlineOutletContextType" });
      continue;
    }

    const name = typeNode.typeName.name;
    const aliasNode = localTypeAliases.get(name);
    if (aliasNode === undefined) {
      context.report({ node: typeNode, messageId: "outletContextTypeNotLocal", data: { name } });
      continue;
    }
    if (!exportedNames.has(name)) {
      // Report at the type alias declaration: that is where `export` needs to be added.
      context.report({
        node: aliasNode,
        messageId: "outletContextTypeNotExported",
        data: { name },
      });
    }
  }
}

function reportChildRole(
  context: Context,
  selfEntries: readonly RouteModuleInfo[],
  routeModules: Record<string, RouteModuleInfo>,
  calls: ESTree.CallExpression[],
  knownNames: ReadonlySet<string>,
  lastImport: ESTree.ImportDeclaration | null,
): void {
  if (calls.length === 0) {
    return;
  }

  // What this module receives is decided by `classifyModuleOutletContext` in
  // `react-router-toolkit` — the same aggregation `typegen` renders into the generated type — so
  // this rule only maps the outcome to diagnostics and never re-derives types itself.
  switch (classifyModuleOutletContext(selfEntries, routeModules)) {
    case "indeterminate": {
      // Some registration's context is unanalyzable, or passed without a usable named type; the
      // parent-role messages on that module cover the fix.
      return;
    }
    case "ambiguous": {
      // Some parent's Outlets disagree; the developer must annotate manually.
      for (const call of calls) {
        context.report({ node: call.callee, messageId: "ambiguousParentOutletContext" });
      }
      return;
    }
    case "undefined": {
      // Context is definitively `undefined` at runtime for every registration, so the call is a
      // misuse.
      for (const call of calls) {
        context.report({ node: call.callee, messageId: "parentOutletPassesNoContext" });
      }
      return;
    }
    case "typed": {
      break;
    }
  }

  // This module receives a precisely typed context: fill in the generated `NearestOutletContext`
  // from `./+toolkit-types/<route>`. The rule assumes `react-router-toolkit typegen` already
  // produced that module and never touches the filesystem to verify it — if typegen has not run,
  // the inserted import fails type checking, which is the signal to run it.
  const expected = NEAREST_OUTLET_CONTEXT_TYPE;
  const moduleSpecifier = toolkitTypesSpecifier(selfEntries[0]!.physicalFile);
  let importPlanned = knownNames.has(expected);

  for (const call of calls) {
    const current = call.typeArguments?.params[0];
    const currentText =
      current === undefined
        ? null
        : normalizeWhitespace(context.sourceCode.text.slice(current.range[0], current.range[1]));
    if (currentText === expected) {
      continue;
    }

    const needsImport = !importPlanned;
    importPlanned = true;
    context.report({
      node: call.typeArguments ?? call.callee,
      messageId: call.typeArguments ? "outdatedOutletContextType" : "missingOutletContextType",
      data: { expected },
      fix: (fixer) => {
        const fixes = [
          call.typeArguments
            ? fixer.replaceTextRange(call.typeArguments.range, `<${expected}>`)
            : fixer.insertTextAfterRange(call.callee.range, `<${expected}>`),
        ];
        if (needsImport) {
          const statement = `import type { ${expected} } from "${moduleSpecifier}";`;
          fixes.push(
            lastImport === null
              ? fixer.insertTextBeforeRange([0, 0], `${statement}\n`)
              : fixer.insertTextAfterRange(lastImport.range, `\n${statement}`),
          );
        }
        return fixes;
      },
    });
  }
}

/**
 * Classify every `<Outlet>` in the module by where it is rendered. React Router renders a module's
 * default export as the route component, so context only reaches descendant routes when the Outlet
 * is reached from the default export — directly, or through a non-exported local component it
 * renders. This mirrors `analyzeRouteModules` in `react-router-toolkit` (which classifies the same
 * way for descendant routes); keep the two in sync.
 *
 * - `reachable`: rendered by the default export ⇒ validated as a context provider.
 * - `exportedComponent`: declared in an exported (non-default) component ⇒ never passes context, so
 *   reported as a misuse.
 *
 * Outlets in unreachable local components are intentionally omitted (dead code we make no claim
 * about).
 */
function classifyOutlets(program: ESTree.Program): {
  reachable: ESTree.JSXOpeningElement[];
  exportedComponent: ESTree.JSXOpeningElement[];
} {
  const scope = collectRuleScope(program);
  if (scope.outletDirect.size === 0 && scope.outletNamespaces.size === 0) {
    return { reachable: [], exportedComponent: [] };
  }

  const reachable: ESTree.JSXOpeningElement[] = [];
  const defaultBody = findDefaultExportBody(program, scope);
  if (defaultBody !== null) {
    collectReachableOutlets(defaultBody, scope, new Set(), reachable);
  }

  const reachableSet = new Set(reachable);
  const exportedComponent: ESTree.JSXOpeningElement[] = [];
  for (const [name, body] of scope.localComponents) {
    if (!scope.exportedNames.has(name)) {
      continue;
    }
    walk(body, (node) => {
      if (
        node.type === "JSXOpeningElement" &&
        isOutletName(node.name, scope.outletDirect, scope.outletNamespaces) &&
        !reachableSet.has(node)
      ) {
        exportedComponent.push(node);
      }
    });
  }
  return { reachable, exportedComponent };
}

/** The body of a component function: a block statement, or an arrow's expression body. */
type ComponentBody = ESTree.FunctionBody | ESTree.Expression;

interface RuleScope {
  readonly outletDirect: Set<string>;
  readonly outletNamespaces: Set<string>;
  readonly exportedNames: Set<string>;
  readonly localComponents: Map<string, ComponentBody>;
}

function collectRuleScope(program: ESTree.Program): RuleScope {
  const scope: RuleScope = {
    outletDirect: new Set(),
    outletNamespaces: new Set(),
    exportedNames: new Set(),
    localComponents: new Map(),
  };

  for (const statement of program.body) {
    if (statement.type === "ImportDeclaration") {
      const source = statement.source.value;
      if (source !== "react-router" && source !== "react-router-dom") {
        continue;
      }
      for (const specifier of statement.specifiers) {
        if (specifier.type === "ImportNamespaceSpecifier") {
          scope.outletNamespaces.add(specifier.local.name);
        } else if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          specifier.imported.name === "Outlet"
        ) {
          scope.outletDirect.add(specifier.local.name);
        }
      }
    } else if (statement.type === "FunctionDeclaration") {
      registerComponent(scope, statement.id?.name, statement.body);
    } else if (statement.type === "VariableDeclaration") {
      registerVariableComponents(scope, statement);
    } else if (statement.type === "ExportNamedDeclaration") {
      const declaration = statement.declaration;
      if (declaration?.type === "FunctionDeclaration") {
        if (declaration.id !== null) {
          scope.exportedNames.add(declaration.id.name);
        }
        registerComponent(scope, declaration.id?.name, declaration.body);
      } else if (declaration?.type === "VariableDeclaration") {
        for (const declarator of declaration.declarations) {
          if (declarator.id.type === "Identifier") {
            scope.exportedNames.add(declarator.id.name);
          }
        }
        registerVariableComponents(scope, declaration);
      }
      for (const specifier of statement.specifiers) {
        if (specifier.local.type === "Identifier") {
          scope.exportedNames.add(specifier.local.name);
        }
      }
    }
  }
  return scope;
}

function registerComponent(
  scope: RuleScope,
  name: string | undefined,
  body: ESTree.FunctionBody | null,
): void {
  if (name !== undefined && body !== null) {
    scope.localComponents.set(name, body);
  }
}

function registerVariableComponents(
  scope: RuleScope,
  declaration: ESTree.VariableDeclaration,
): void {
  for (const declarator of declaration.declarations) {
    if (declarator.id.type !== "Identifier" || declarator.init === null) {
      continue;
    }
    const init = declarator.init;
    if (
      (init.type === "ArrowFunctionExpression" || init.type === "FunctionExpression") &&
      init.body !== null
    ) {
      scope.localComponents.set(declarator.id.name, init.body);
    }
  }
}

function findDefaultExportBody(program: ESTree.Program, scope: RuleScope): ComponentBody | null {
  for (const statement of program.body) {
    if (statement.type !== "ExportDefaultDeclaration") {
      continue;
    }
    const declaration = statement.declaration;
    if (
      declaration.type === "FunctionDeclaration" ||
      declaration.type === "FunctionExpression" ||
      declaration.type === "ArrowFunctionExpression"
    ) {
      return declaration.body;
    }
    if (declaration.type === "Identifier") {
      return scope.localComponents.get(declaration.name) ?? null;
    }
    return null;
  }
  return null;
}

function collectReachableOutlets(
  body: ComponentBody,
  scope: RuleScope,
  visited: Set<string>,
  out: ESTree.JSXOpeningElement[],
): void {
  walkReachableBody(body, (node) => {
    if (node.type !== "JSXOpeningElement") {
      return;
    }
    if (isOutletName(node.name, scope.outletDirect, scope.outletNamespaces)) {
      out.push(node);
      return;
    }
    if (node.name.type !== "JSXIdentifier") {
      return;
    }
    const name = node.name.name;
    if (scope.localComponents.has(name) && !scope.exportedNames.has(name) && !visited.has(name)) {
      visited.add(name);
      collectReachableOutlets(scope.localComponents.get(name)!, scope, visited, out);
    }
  });
}

function walkReachableBody(node: unknown, visit: (node: ESTree.Node) => void): void {
  if (Array.isArray(node)) {
    for (const item of node) {
      walkReachableBody(item, visit);
    }
    return;
  }
  if (node === null || typeof node !== "object") {
    return;
  }
  if (typeof (node as { type?: unknown }).type === "string") {
    const astNode = node as ESTree.Node;
    if (isFunctionOrClassNode(astNode)) {
      return;
    }
    visit(astNode);
  }
  for (const [key, value] of Object.entries(node)) {
    if (key !== "parent") {
      walkReachableBody(value, visit);
    }
  }
}

function isFunctionOrClassNode(node: ESTree.Node): boolean {
  return (
    node.type === "FunctionDeclaration" ||
    node.type === "FunctionExpression" ||
    node.type === "ArrowFunctionExpression" ||
    node.type === "ClassDeclaration" ||
    node.type === "ClassExpression"
  );
}

/** Depth-first walk over the AST, skipping `parent` back-references to avoid cycles. */
function walk(node: unknown, visit: (node: ESTree.Node) => void): void {
  if (Array.isArray(node)) {
    for (const item of node) {
      walk(item, visit);
    }
    return;
  }
  if (node === null || typeof node !== "object") {
    return;
  }
  if (typeof (node as { type?: unknown }).type === "string") {
    visit(node as ESTree.Node);
  }
  for (const [key, value] of Object.entries(node)) {
    if (key !== "parent") {
      walk(value, visit);
    }
  }
}

function isOutletName(
  name: ESTree.JSXOpeningElement["name"],
  directNames: ReadonlySet<string>,
  namespaceNames: ReadonlySet<string>,
): boolean {
  if (name.type === "JSXIdentifier") {
    return directNames.has(name.name);
  }
  if (name.type === "JSXMemberExpression") {
    return (
      name.object.type === "JSXIdentifier" &&
      namespaceNames.has(name.object.name) &&
      name.property.name === "Outlet"
    );
  }
  return false;
}

function normalizeWhitespace(value: string): string {
  return value.replaceAll(/\s+/g, " ").trim();
}

export default typeSafeOutletContext;
